
project_id = "amhznlnhrrugxatbeayo"

[functions.meta-tags]
verify_jwt = false

[functions.password-reset-request]
verify_jwt = false

[functions.send-daily-notifications]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
